Nhom5conbao_WebsiteNoiThat/Models/Cart.cs
using System;
using System.Collections.Generic;

namespace Nhom5conbao_WebsiteNoiThat.Models;

public partial class Cart
{
    public int IdCart { get; set; }

    public DateTime? Datebegin { get; set; }

    public int? Hide { get; set; }

    public int? IdUsers { get; set; }

    public virtual ICollection<CartDetail> CartDetails { get; set; } = new List<CartDetail>();

    public virtual User? IdUsersNavigation { get; set; }
}

Nhom5conbao_WebsiteNoiThat/ViewModels/CartViewModel.cs
using Nhom5conbao_WebsiteNoiThat.Models;

namespace Nhom5conbao_WebsiteNoiThat.ViewModels
{
    public class CartViewModel
    {
        public List<Menu> Menus { get; set; }
        public List<Blog> Blogs { get; set; }
        public List<CartItem> CartItems { get; set; }

        public int PageNumber { get; set; }
        public int TotalPages { get; set; }
    }
}

Nhom5conbao_WebsiteNoiThat/Controllers/CartController.cs
using Nhom5conbao_WebsiteNoiThat.Models;
using Nhom5conbao_WebsiteNoiThat.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Nhom5conbao_WebsiteNoiThat.Models;

namespace Nhom5conbao_WebsiteNoiThat.Controllers
{
    public class CartController : Controller
    {
        private readonly WebNoiThatContext _context;
        private const string CartSession = "CartSession";
        public CartController(WebNoiThatContext context)
        {
            _context = context;
        }
        //-----------------------------------------------------------------------
        //Task #01. Thông tin giỏ hàng
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            var menus = await _context.Menus.Where(m => m.Hide == 0).OrderBy(m => m.Order).ToListAsync();
            var blogs = await _context.Blogs.Where(m => m.Hide == 0).OrderBy(m => m.Order).Take(2).ToListAsync();
            var cart = HttpContext.Session.GetString(CartSession);
            var list = new List<CartItem>();
            if (!string.IsNullOrEmpty(cart))
            {
                list = JsonConvert.DeserializeObject<List<CartItem>>(cart);
            }

            // Đếm tổng số trang
            int pageSize = 3; // Số lượng item trên mỗi trang
            int totalItems = list.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var cartViewModel = new CartViewModel
            {
                Menus = menus,
                Blogs = blogs,
                CartItems = list.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList(),
                PageNumber = pageNumber,
                TotalPages = totalPages
            };

            return View(cartViewModel);
        }

        //Task #02. Thêm một sản phẩm vào giỏ hàng
        //------------------------------------------------------------------
        public IActionResult AddItem(int ProductId, int Quantity)
        {
            var product = _context.Products.Find(ProductId);
            var cart = HttpContext.Session.GetString(CartSession);
            if (!string.IsNullOrEmpty(cart))
            {
                var list = JsonConvert.DeserializeObject<List<CartItem>>(cart);
                if (list.Exists(x => x.Product.IdPro == ProductId))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.IdPro == ProductId)
                        {
                            item.Quantity += Quantity;
                        }
                    }
                }
                else
                {
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = Quantity;
                    list.Add(item);
                }
                HttpContext.Session.SetString(CartSession, JsonConvert.SerializeObject(list));
            }
            else
            {
                var item = new CartItem();
                item.Product = product;
                item.Quantity = Quantity;
                var list = new List<CartItem>();
                list.Add(item);
                HttpContext.Session.SetString(CartSession, JsonConvert.SerializeObject(list));
            }
            return RedirectToAction("Index");
        }
        //Task #03. Cập nhật giỏ hàng
        //----------------------------------------------
        public IActionResult DeleteAll()
        {
            HttpContext.Session.Remove(CartSession);
            return Json(new
            {
                status = true
            });
        }
        public IActionResult Delete(int id)
        {
            var sessionCart = JsonConvert.DeserializeObject<List<CartItem>>(HttpContext.Session.GetString(CartSession));
            sessionCart.RemoveAll(x => x.Product.IdPro == id);
            HttpContext.Session.SetString(CartSession,JsonConvert.SerializeObject(sessionCart));
            return Json(new
            {
                status = true
            });
        }
        public IActionResult Update(string cartModel)
        {
            var jsonCart = JsonConvert.DeserializeObject<List<CartItem>>(cartModel);
            var sessionCart = JsonConvert.DeserializeObject<List<CartItem>>(HttpContext.Session.GetString(CartSession));
            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.IdPro == item.Product.IdPro);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }
            HttpContext.Session.SetString(CartSession,JsonConvert.SerializeObject(sessionCart));
            return Json(new
            {
                status = true
            });
        }
        //----------------------------------------------
        //Task #04. Hoàn tất giỏ hàng
        [HttpGet]
        public async Task<IActionResult> Payment(string name)
        {
            var menus = await _context.Menus.Where(m => m.Hide == 0).OrderBy(m => m.Order).ToListAsync();
            var blogs = await _context.Blogs.Where(m => m.Hide == 0).OrderBy(m => m.Order).Take(2).ToListAsync();
            var cart = HttpContext.Session.GetString(CartSession);
            var list = new List<CartItem>();
            if (!string.IsNullOrEmpty(cart))
            {
                list = JsonConvert.DeserializeObject<List<CartItem>>(cart);
            }
            var cartViewModel = new CartViewModel
            {
                Menus = menus,
                Blogs = blogs,
                CartItems = list
            };
            return View(cartViewModel);
        }
        //------------------------------------------------
        //Cập nhật CartController.cs, thêm các hàm 
        [HttpPost]
        public async Task<IActionResult> Payment()
        {
            var order = new Cart();
            order.Hide = 0;
            order.Datebegin = DateTime.Now;
            var users = new User();
            if (User.Identity.IsAuthenticated)
            {
                string username = User.Identity.Name;
                if (username != null) users = await _context.Users.FirstOrDefaultAsync(m => m.Username == username);
            }
            order.IdUsers = users.IdUsers;
            try
            {
                _context.Carts.Add(order);
                _context.SaveChanges();
                var id = order.IdCart;
                var cart =
                JsonConvert.DeserializeObject<List<CartItem>>(HttpContext.Session.GetString(CartSession));
                foreach (var item in cart)
                {
                    var detail = new CartDetail();
                    detail.IdPro = item.Product.IdPro;
                    detail.IdCart = id;
                    detail.SoldNum = item.Quantity;
                    detail.Hide = 0;
                    _context.CartDetails.Add(detail);
                    _context.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return Redirect("/hoan-thanh");
        }
        public async Task<IActionResult> Success()
        {
            var menus = await _context.Menus.Where(m => m.Hide == 0).OrderBy(m =>
            m.Order).ToListAsync();
            var blogs = await _context.Blogs.Where(m => m.Hide == 0).OrderBy(m =>
            m.Order).Take(2).ToListAsync();
            var cartViewModel = new CartViewModel
            {
                Menus = menus,
                Blogs = blogs
            };
            return View(cartViewModel);
        }

        //-------------------------------------------------------------------------------------
        public async Task<IActionResult> _MenuPartial()
        {
            return PartialView();
        }
        public async Task<IActionResult> _BlogPartial()
        {
            return PartialView();
        }
    }
}

Nhom5conbao_WebsiteNoiThat/Views/Cart/Index.cshtml
@model Nhom5conbao_WebsiteNoiThat.ViewModels.CartViewModel

<div class="try_lt_st_main_wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 try_lt_st_heading_wrapper">
                <div class="try_recent_mob_heading_wrapper">
                    <h2> GIỎ HÀNG CỦA SHOP ĐỒ NỘI THẤT - NHÓM 5 CON BÁO </h2>
                    <p>
                        <span class="try_left_dots"></span>---<span class="try_right_dots"></span>
                    </p>
                </div>
            </div>
            <!--------------------------------------------------------------------------------------------------->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">Giỏ hàng của bạn</div>
                    <div class="panel-body">
                        @if (Model.CartItems.Count > 0)
                        {
                            <table class="table table-bordered">
                                <thead>
                                    <tr style="text-align:center;font-weight:bold">
                                        <td>Mã SP</td>
                                        <td>Tên SP</td>
                                        <td>Ảnh SP</td>
                                        <td>Số lượng</td>
                                        <td>Đơn giá</td>
                                        <td>Thành tiền</td>
                                        <td></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.CartItems)
                                    {
                                        <tr>
                                            <td style="text-align:center">@item.Product.IdPro</td>
                                            <td>@item.Product.NamePro</td>
                                            <td>
                                                <img src="~/images/content/@item.Product.Img1"
                                                     width="100" />
                                            </td>
                                            <td><input type="text" class="txtQuantity" data-id="@item.Product.IdPro" value="@item.Quantity" /></td>
                                            <td style="text-align:center">
                                                @String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"),
                                                         "{0:c}", item.Product.Price.GetValueOrDefault(0))
                                            </td>
                                            <td style="text-align:center">
                                                @String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"),
                                                         "{0:c}", item.Product.Price.GetValueOrDefault(0) * item.Quantity)
                                            </td>
                                            <td><a href="#" data-id="@item.Product.IdPro" class="btn-delete">Xoá</a></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <button id="btnContinue" class="btn btn-primary">Tiếp tục mua hàng</button>
                            <button id="btnUpdate" class="btn btn-info">Cập nhật giỏ hàng</button>
                            <button id="btnDeleteAll" class="btn btn-danger">Xoá giỏ hàng</button>
                            <button id="btnPayment" class="btn btn-success">Thanh toán</button>
                        }
                        else
                        {
                            <div style="margin-top:10px;margin-bottom:10px;margin-left:auto; margin-right:auto">
                                <span class="alert alert-danger">
                                    Bạn chưa có sản phẩm nào trong giỏ hàng
                                </span>
                            </div>
                        }
                    </div>
                    <div class="panel-footer text-center">
                        <ul class="pagination pagination-centered">
                            @for (int i = 1; i <= Model.TotalPages; i++)
                            {
                                <li class="@(i == Model.PageNumber ? "active" : "")"><a href="@Url.Action("Index", new { pageNumber = i })">@i</a></li>
                            }
                        </ul>
                    </div>
                </div>
                @section scripts {
                    <script src="~/js/cart.js"></script>
                }
            </div>
            <!--------------------------------------------------------------------------------------------------->
        </div>
    </div>
</div>
 

Nhom5conbao_WebsiteNoiThat/Views/Cart/Payment.cshtml
@model Nhom5conbao_WebsiteNoiThat.ViewModels.CartViewModel

<div class="try_lt_st_main_wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 try_lt_st_heading_wrapper">
                <div class="try_recent_mob_heading_wrapper">
                    <h2> THANH TOÁN ĐƠN HÀNG - SHOP ĐỒ NỘI THẤT - NHÓM 5 CON BÁO </h2>
                    <p>
                        <span class="try_left_dots"></span>---<span class="try_right_dots"></span>
                    </p>
                </div>
            </div>
            <!--------------------------------------------------------------------------------------------------->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">Tiến hành thanh toán</div>
                    <div class="panel-body">
                        @if (Model.CartItems.Count > 0)
                        {
                            <table class="table table-bordered">
                                <thead>
                                    <tr style="text-align:center;font-weight:bold">
                                        <td>Mã SP</td>
                                        <td>Tên SP</td>
                                        <td>Ảnh SP</td>
                                        <td>Số lượng</td>
                                        <td>Đơn giá</td>
                                        <td>Thành tiền</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.CartItems)
                                    {
                                        <tr>
                                            <td style="text-align:center">@item.Product.IdPro</td>
                                            <td>@item.Product.NamePro</td>
                                            <td>
                                                <img src="~/images/content/@item.Product.Img1" width="100" />
                                            </td>
                                            <td><input type="text" class="txtQuantity" dataid="@item.Product.IdPro" value="@item.Quantity" disabled /></td>
                                            <td style="text-align:center">
                                                @String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"),
                                                         "{0:c}", item.Product.Price.GetValueOrDefault(0))
                                            </td>
                                            <td style="text-align:center">
                                                @String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"),
                                                         "{0:c}", item.Product.Price.GetValueOrDefault(0) * item.Quantity)
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            @using (Html.BeginForm("Payment", "Cart", FormMethod.Post))
                            {
                                <button type="submit" class="btn btn-success pull-right">Gửi đơn hàng </button>
                            }
                        }
                        else
                        {
                            <div style="margin-top:10px;margin-bottom:10px;margin-left:auto; marginright:auto">
                                <span class="alert alert-danger"> Bạn chưa có sản phẩm nào trong giỏ hàng</span>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <!--------------------------------------------------------------------------------------------------->
        </div>
    </div>
</div>

Nhom5conbao_WebsiteNoiThat/Views/Cart/Success.cshtml
@model Nhom5conbao_WebsiteNoiThat.ViewModels.CartViewModel

<div class="try_lt_st_main_wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 try_lt_st_heading_wrapper">
                <div class="try_recent_mob_heading_wrapper">
                    <h2> SHOP ĐỒ NỘI THẤT - NHÓM 5 CON BÁO </h2>
                    <p>
                        <span class="try_left_dots"></span>---<span class="try_right_dots"></span>
                    </p>
                </div>
            </div>
            <!--------------------------------------------------------------------------------------------------->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="alert alert-success">
                    Bạn vừa mua hàng thành công! Chúng tôi sẽ gọi điện để xác nhận đơn hàng. SHOP ĐỒ NỘI THẤT - NHÓM 5 CON BÁO xin cảm ơn!
                </div>
            </div>
            <!--------------------------------------------------------------------------------------------------->
        </div>
    </div>
</div>